language: java
services:
  - xvfb
jdk:
  - openjdk8
addons:
  firefox: "latest-esr"

before_install:
  - "export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH"
  - if [ $(phantomjs --version) != '2.1.1' ]; then 
      rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs;
      wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2;
      tar -xvf $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; 
    fi
script: mvn verify
